ray.train.UserCallback.after\_exception
=======================================

.. currentmodule:: ray.train

.. automethod:: UserCallback.after_exception